name: 🪲 Report a bug
description: Create a bug report
title: "Summary of bug"
labels: ["potential bug"]
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Please use one of the [support links](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

  - type: dropdown
    attributes:
      label: Did you test the latest firmware release?
      description: >-
        Always try the latest firmware build to make sure the issue you are reporting is not already fixed.
      options:
        - Yes, and the problem still exists.
        - No, but I will test it now!
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: Did you test with the stock Creality firmware?
      description: >-
        It's very important to know whether this bug is present in stock firmware or we have introduced some regression.
      options:
        - I have tested, stock firmware has not such problem.
        - I have tested, stock firmware does have this problem.
        - No, but I will test it now!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Bug Details
  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.
      value: >-
        I did X and expected printer do Y, but instead it did Z. It also produced weird movements and did a lot of noises.
        Eventually, my the result was not what I expected.
  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: dropdown
    attributes:
      label: Your Slicer
      description: Which slicer do you use?
      options:
        - Prusa Slicer
        - Orca Slicer
        - Creality Print
        - Cura

  - type: dropdown
    attributes:
      label: Host Software
      description: Do you use OctoPrint or print from SD?
      options:
        - SD Card
        - OctoPrint

  - type: markdown
    attributes:
      value: |
        ### Optional items to include:
        - A G-Code file that exposes the problem, if not affecting _all_ G-code.
        - Log output from the serial console
        - Images or videos demonstrating the problem, if it helps to make it clear.

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        If you've made any other modifications to the firmware, please describe them in detail.
